BAN_GIFS = [
    "https://tenor.com/bqhVe.gif",
    "https://tenor.com/bsHe5.gif",
    "https://j.gifs.com/y5Pr8z.gif",
    "https://tenor.com/bfvQv.gif",
    "https://j.gifs.com/lO0lv6.gif",
    "https://tenor.com/bGMhb.gif",
    "https://tenor.com/bjZai.gif",
    "https://media.giphy.com/media/fe4dDMD2cAU5RfEaCU/giphy.gif",
    "https://tenor.com/bndta.gif",
    "https://tenor.com/bkyIr.gif",
    "https://media.giphy.com/media/UBqgQxKnUJqb8oZ2zc/giphy.gif",
    "https://media.giphy.com/media/tanIENriCOil3ndF3V/giphy.gif",
    "https://media.giphy.com/media/fwX4RUzdkdx9XUGow4/giphy.gif",
    "https://media.giphy.com/media/XVLfZCU6jDvMYqF1xS/giphy.gif",
    "https://media.giphy.com/media/BSAZJvFOOR0VqREKMg/giphy.gif",
    "https://media.giphy.com/media/CI4aCJUjJDJEj3Jgo4/giphy-downsized-large.gif",
    "https://media.giphy.com/media/0jcrQmPmyI5U532qL2/giphy.gif",
]

KICK_GIFS = [
    "https://tenor.com/bizBJ.gif",
    "https://tenor.com/bjPvj.gif",
    "https://tenor.com/bJMx3.gif",
    "https://tenor.com/bJCGL.gif",
    "https://tenor.com/bsIMJ.gif",
    "https://tenor.com/buURG.gif",
    "https://tenor.com/bNOj9.gif",
    "https://tenor.com/NfK8.gif",
    "https://tenor.com/ymZn.gif",
    "https://tenor.com/77Lu.gif",
    "https://tenor.com/bPD4I.gif",
    "https://tenor.com/bOGXo.gif",
    "https://tenor.com/bDLqs.gif",
    "https://tenor.com/bxUsN.gif",
    "https://media.giphy.com/media/u2LJ0n4lx6jF6/giphy.gif",
    "https://media.giphy.com/media/BSAZJvFOOR0VqREKMg/giphy.gif",
    "https://media.giphy.com/media/eDR7j2vjCFOUMJ9rT2/giphy.gif",
    "https://media.giphy.com/media/ERNKP5G7ihZNW6VW4Q/giphy.gif",
    "https://media.giphy.com/media/1r6xks2F0iHfbNvt4p/giphy.gif",
    "https://media.giphy.com/media/M7j1rkxm0X5z30Hyrs/giphy.gif",
    "https://media.giphy.com/media/rad9oJzU4hVafD8ZnT/giphy.gif",
    "https://media.giphy.com/media/TcliN5WDKBbnUQ15H3/giphy.gif",
    "https://media.giphy.com/media/y9pfUqY3uaT1MPXxYM/giphy.gif",
]

MUTE_GIFS = [
    "https://media.giphy.com/media/MpCxz9VLh6t8ceRb0r/giphy.gif",
    "https://media.giphy.com/media/HWl1atKEPAWcw/giphy.gif",
    "https://media.giphy.com/media/1xkynOSsb8eFpbEood/giphy.gif",
    "https://media.giphy.com/media/LmUAM5ImMNZd0nnkvn/giphy.gif",
    "https://media.giphy.com/media/JNlXHSSioDe7YGTC7D/giphy.gif",
    "https://media.giphy.com/media/t0iSe43jX8JH0Hb95a/giphy.gif",
    "https://media.giphy.com/media/P4CXV70NTC0umRI61S/giphy.gif",
    "https://media.giphy.com/media/Z0WPxDF7zpIHVPrYUN/giphy.gif",
    "https://media.giphy.com/media/gJS1pGTbXlSCWUe2pg/giphy.gif",
    "https://media.giphy.com/media/SIoetMN7j96O5perEV/giphy.gif",
    "https://media.giphy.com/media/PBZrH2uy9E5rPruuCX/giphy.gif",
    "https://media.giphy.com/media/Cew2qzlug9t3ACYrD5/giphy.gif",
    "https://media.giphy.com/media/PtIm7eUGKYIZbknqsO/giphy.gif",
    "https://media.giphy.com/media/EKbCY8OgdATSGBekxM/giphy.gif",
]

StartPic = [
    "https://graph.org/file/aec2ac5c2abaf815aa0ef.jpg",
    "https://graph.org/file/3fc2ec81d728c087458a0.jpg",
    "https://graph.org/file/e7377e6eefa874a9d71fc.jpg",
]
